[package]
name = "git-localbranchtidy"
version = "0.1.0"
edition = "2024"
description = "Delete all branches that have been merged into `main` or `master`."
repository = "https://github.com/plicease/git-localbranchtidy"
license = "MIT"

[dependencies]
anyhow = "1.0.104"


[package.metadata.deb]
maintainer = "Nobody <devnull@wdlabs.com>"
copyright = "Nobody"
extended-description = """\
Delete all branches that have been merged into `main` or `master`."""
section = "utils"
priority = "optional"
assets = [
    ["target/release/git-localbranchtidy", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/git-localbranchtidy/README.md", "644"],
    ["LICENSE", "usr/share/doc/git-localbranchtidy/LICENSE", "644"],
]

